---
# ServerSetup uses git but doesn't install it.
- name: Install git
  ansible.builtin.package:
    name:
      - git

- name: Create the /opt/ServerSetup directory
  ansible.builtin.file:
    mode: u=rwx,g=rx,o=rx
    path: /opt/ServerSetup
    state: directory

- name: Download and untar the ServerSetup tarball
  ansible.builtin.unarchive:
    dest: /opt/ServerSetup
    extra_opts:
      - --strip-components=1
    remote_src: true
    src: https://api.github.com/repos/noahpowers/ServerSetup/tarball/master

- name: Copy the PCA-specific ServerSetup script
  ansible.builtin.copy:
    dest: /opt/ServerSetup/classic_pca_serversetup.sh
    mode: u=rwx,g=rx,o=rx
    src: pca_serversetup.sh
